
var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},f),ba=[],ca="./this.program",da=(a,b)=>{throw b;},ea="object"==typeof window,h="function"==typeof importScripts,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,m="",w,z,ha;
if(fa){var fs=require("fs"),ia=require("path");m=h?ia.dirname(m)+"/":__dirname+"/";w=(a,b)=>{a=a.startsWith("file://")?new URL(a):ia.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ha=a=>{a=w(a,!0);a.buffer||(a=new Uint8Array(a));return a};z=(a,b,c)=>{a=a.startsWith("file://")?new URL(a):ia.normalize(a);fs.readFile(a,function(d,e){d?c(d):b(e.buffer)})};1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);process.on("uncaughtException",
function(a){if(!(a instanceof ja))throw a;});process.on("unhandledRejection",function(a){throw a;});da=(a,b)=>{if(noExitRuntime)throw process.exitCode=a,b;b instanceof ja||B("exiting due to exception: "+b);process.exit(a)};f.inspect=function(){return"[Emscripten Module object]"}}else if(ea||h)h?m=self.location.href:"undefined"!=typeof document&&document.currentScript&&(m=document.currentScript.src),m=0!==m.indexOf("blob:")?m.substr(0,m.replace(/[?#].*/,"").lastIndexOf("/")+1):"",w=a=>{var b=new XMLHttpRequest;
b.open("GET",a,!1);b.send(null);return b.responseText},h&&(ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),z=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ka=f.print||console.log.bind(console),B=f.printErr||console.warn.bind(console);Object.assign(f,aa);aa=null;f.arguments&&(ba=f.arguments);
f.thisProgram&&(ca=f.thisProgram);f.quit&&(da=f.quit);var C;f.wasmBinary&&(C=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!=typeof WebAssembly&&E("no native wasm support detected");var la,ma=!1,na="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function F(a,b){for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&na)return na.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|g);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c}
function oa(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var r=a.charCodeAt(++g);k=65536+((k&1023)<<10)|r&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function pa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var G,qa,ra,H,I,sa=[],ta=[],ua=[],va=[];function wa(){var a=f.preRun.shift();sa.unshift(a)}var J=0,xa=null,L=null;function ya(){J++;f.monitorRunDependencies&&f.monitorRunDependencies(J)}function za(){J--;f.monitorRunDependencies&&f.monitorRunDependencies(J);if(0==J&&(null!==xa&&(clearInterval(xa),xa=null),L)){var a=L;L=null;a()}}
function E(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";B(a);ma=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function Aa(){return M.startsWith("data:application/octet-stream;base64,")}var M;M="svg2ass.wasm";if(!Aa()){var Ba=M;M=f.locateFile?f.locateFile(Ba,m):m+Ba}function Ca(){var a=M;try{if(a==M&&C)return new Uint8Array(C);if(ha)return ha(a);throw"both async and sync fetching of the wasm failed";}catch(b){E(b)}}
function Da(){if(!C&&(ea||h)){if("function"==typeof fetch&&!M.startsWith("file://"))return fetch(M,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+M+"'";return a.arrayBuffer()}).catch(function(){return Ca()});if(z)return new Promise(function(a,b){z(M,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ca()})}var N,Ea;
function ja(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function Fa(a){for(;0<a.length;)a.shift()(f)}
var Ga=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},O=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ga(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ha=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},Ia=a=>{if("/"===
a)return"/";a=O(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function Ja(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return()=>{crypto.getRandomValues(a);return a[0]}}if(fa)try{var b=require("crypto");return()=>b.randomBytes(1)[0]}catch(c){}return()=>E("randomDevice")}
function Ka(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ga(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}function La(a){var b=Array(pa(a)+1);a=oa(a,b,0,b.length);b.length=a;return b}var Ma=[];function Na(a,b){Ma[a]={input:[],output:[],J:b};Oa(a,Pa)}
var Pa={open:function(a){var b=Ma[a.node.rdev];if(!b)throw new P(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.J.fsync(a.tty)},fsync:function(a){a.tty.J.fsync(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.J.Y)throw new P(60);for(var e=0,g=0;g<d;g++){try{var k=a.tty.J.Y(a.tty)}catch(r){throw new P(29);}if(void 0===k&&0===e)throw new P(6);if(null===k||void 0===k)break;e++;b[c+g]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.J.R)throw new P(60);try{for(var e=
0;e<d;e++)a.tty.J.R(a.tty,b[c+e])}catch(g){throw new P(29);}d&&(a.node.timestamp=Date.now());return e}},Qa={Y:function(a){if(!a.input.length){var b=null;if(fa){var c=Buffer.alloc(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,-1)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==
b&&(b+="\n"));if(!b)return null;a.input=La(b)}return a.input.shift()},R:function(a,b){null===b||10===b?(ka(F(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(ka(F(a.output,0)),a.output=[])}},Ra={R:function(a,b){null===b||10===b?(B(F(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(B(F(a.output,0)),a.output=[])}},Q={B:null,C:function(){return Q.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===
(c&61440)||4096===(c&61440))throw new P(63);Q.B||(Q.B={dir:{node:{G:Q.s.G,A:Q.s.A,lookup:Q.s.lookup,L:Q.s.L,rename:Q.s.rename,unlink:Q.s.unlink,rmdir:Q.s.rmdir,readdir:Q.s.readdir,symlink:Q.s.symlink},stream:{H:Q.u.H}},file:{node:{G:Q.s.G,A:Q.s.A},stream:{H:Q.u.H,read:Q.u.read,write:Q.u.write,T:Q.u.T,P:Q.u.P,ba:Q.u.ba}},link:{node:{G:Q.s.G,A:Q.s.A,readlink:Q.s.readlink},stream:{}},V:{node:{G:Q.s.G,A:Q.s.A},stream:Sa}});c=Ta(a,b,c,d);16384===(c.mode&61440)?(c.s=Q.B.dir.node,c.u=Q.B.dir.stream,c.o=
{}):32768===(c.mode&61440)?(c.s=Q.B.file.node,c.u=Q.B.file.stream,c.v=0,c.o=null):40960===(c.mode&61440)?(c.s=Q.B.link.node,c.u=Q.B.link.stream):8192===(c.mode&61440)&&(c.s=Q.B.V.node,c.u=Q.B.V.stream);c.timestamp=Date.now();a&&(a.o[b]=c,a.timestamp=c.timestamp);return c},pa:function(a){return a.o?a.o.subarray?a.o.subarray(0,a.v):new Uint8Array(a.o):new Uint8Array(0)},W:function(a,b){var c=a.o?a.o.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.o,a.o=new Uint8Array(b),
0<a.v&&a.o.set(c.subarray(0,a.v),0))},ka:function(a,b){if(a.v!=b)if(0==b)a.o=null,a.v=0;else{var c=a.o;a.o=new Uint8Array(b);c&&a.o.set(c.subarray(0,Math.min(b,a.v)));a.v=b}},s:{G:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.v:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);
b.fa=4096;b.blocks=Math.ceil(b.size/b.fa);return b},A:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&Q.ka(a,b.size)},lookup:function(){throw Ua[44];},L:function(a,b,c,d){return Q.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=R(b,c)}catch(g){}if(d)for(var e in d.o)throw new P(55);}delete a.parent.o[a.name];a.parent.timestamp=Date.now();a.name=c;b.o[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,
b){delete a.o[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=R(a,b),d;for(d in c.o)throw new P(55);delete a.o[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.o)a.o.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=Q.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new P(28);return a.link}},u:{read:function(a,b,c,d,e){var g=a.node.o;if(e>=a.node.v)return 0;a=Math.min(a.node.v-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,
e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.o||a.o.subarray)){if(g)return a.o=b.subarray(c,c+d),a.v=d;if(0===a.v&&0===e)return a.o=b.slice(c,c+d),a.v=d;if(e+d<=a.v)return a.o.set(b.subarray(c,c+d),e),d}Q.W(a,e+d);if(a.o.subarray&&b.subarray)a.o.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.o[e+g]=b[c+g];a.v=Math.max(a.v,e+d);return d},H:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&
61440)&&(b+=a.node.v);if(0>b)throw new P(28);return b},T:function(a,b,c){Q.W(a.node,b+c);a.node.v=Math.max(a.node.v,b+c)},P:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new P(43);a=a.node.o;if(e&2||a.buffer!==G.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;E();b=void 0;if(!b)throw new P(48);G.set(a,b)}else c=!1,b=a.byteOffset;return{sa:b,oa:c}},ba:function(a,b,c,d){Q.u.write(a,b,0,d,c,!1);return 0}}};
function Va(a,b,c){var d="al "+a;z(a,e=>{e||E('Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&za(d)},()=>{if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&ya(d)}
var Wa=null,Xa={},Ya=[],Za=1,S=null,$a=!0,P=null,Ua={},T=(a,b={})=>{a=Ka(a);if(!a)return{path:"",node:null};b=Object.assign({X:!0,S:0},b);if(8<b.S)throw new P(32);a=a.split("/").filter(k=>!!k);for(var c=Wa,d="/",e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;c=R(c,a[e]);d=O(d+"/"+a[e]);c.K&&(!g||g&&b.X)&&(c=c.K.root);if(!g||b.M)for(g=0;40960===(c.mode&61440);)if(c=ab(d),d=Ka(Ha(d),c),c=T(d,{S:b.S+1}).node,40<g++)throw new P(32);}return{path:d,node:c}},U=a=>{for(var b;;){if(a===a.parent)return a=
a.C.aa,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},bb=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%S.length},R=(a,b)=>{var c;if(c=(c=cb(a,"x"))?c:a.s.lookup?0:2)throw new P(c,a);for(c=S[bb(a.id,b)];c;c=c.I){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.s.lookup(a,b)},Ta=(a,b,c,d)=>{a=new db(a,b,c,d);b=bb(a.parent.id,a.name);a.I=S[b];return S[b]=a},eb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},fb=a=>{var b=["r","w",
"rw"][a&3];a&512&&(b+="w");return b},cb=(a,b)=>{if($a)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},gb=(a,b)=>{try{return R(a,b),20}catch(c){}return cb(a,"wx")},hb=(a=0)=>{for(;4096>=a;a++)if(!Ya[a])return a;throw new P(33);},jb=(a,b)=>{ib||(ib=function(){this.D={}},ib.prototype={},Object.defineProperties(ib.prototype,{object:{get:function(){return this.node},set:function(c){this.node=c}},flags:{get:function(){return this.D.flags},
set:function(c){this.D.flags=c}},position:{get:function(){return this.D.position},set:function(c){this.D.position=c}}}));a=Object.assign(new ib,a);b=hb(b);a.fd=b;return Ya[b]=a},Sa={open:a=>{a.u=Xa[a.node.rdev].u;a.u.open&&a.u.open(a)},H:()=>{throw new P(70);}},Oa=(a,b)=>{Xa[a]={u:b}},kb=(a,b)=>{var c="/"===b,d=!b;if(c&&Wa)throw new P(10);if(!c&&!d){var e=T(b,{X:!1});b=e.path;e=e.node;if(e.K)throw new P(10);if(16384!==(e.mode&61440))throw new P(54);}b={type:a,ra:{},aa:b,ja:[]};a=a.C(b);a.C=b;b.root=
a;c?Wa=a:e&&(e.K=b,e.C&&e.C.ja.push(b))},V=(a,b,c)=>{var d=T(a,{parent:!0}).node;a=Ia(a);if(!a||"."===a||".."===a)throw new P(28);var e=gb(d,a);if(e)throw new P(e);if(!d.s.L)throw new P(63);return d.s.L(d,a,b,c)},lb=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);return V(a,b|8192,c)},mb=(a,b)=>{if(!Ka(a))throw new P(44);var c=T(b,{parent:!0}).node;if(!c)throw new P(44);b=Ia(b);var d=gb(c,b);if(d)throw new P(d);if(!c.s.symlink)throw new P(63);c.s.symlink(c,b,a)},nb=a=>{var b=T(a,{parent:!0}).node;if(!b)throw new P(44);
var c=Ia(a);a=R(b,c);a:{try{var d=R(b,c)}catch(g){d=g.F;break a}var e=cb(b,"wx");d=e?e:16384===(d.mode&61440)?31:0}if(d)throw new P(d);if(!b.s.unlink)throw new P(63);if(a.K)throw new P(10);b.s.unlink(b,c);b=bb(a.parent.id,a.name);if(S[b]===a)S[b]=a.I;else for(b=S[b];b;){if(b.I===a){b.I=a.I;break}b=b.I}},ab=a=>{a=T(a).node;if(!a)throw new P(44);if(!a.s.readlink)throw new P(28);return Ka(U(a.parent),a.s.readlink(a))},ob=(a,b)=>{a="string"==typeof a?T(a,{M:!0}).node:a;if(!a.s.A)throw new P(63);a.s.A(a,
{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},qb=(a,b,c)=>{if(""===a)throw new P(44);if("string"==typeof b){var d=eb[b];if("undefined"==typeof d)throw Error("Unknown file open mode: "+b);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=O(a);try{e=T(a,{M:!(b&131072)}).node}catch(g){}}d=!1;if(b&64)if(e){if(b&128)throw new P(20);}else e=V(a,c,0),d=!0;if(!e)throw new P(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new P(54);
if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==fb(b)||b&512)?31:cb(e,fb(b)):44))throw new P(c);if(b&512&&!d){c=e;c="string"==typeof c?T(c,{M:!0}).node:c;if(!c.s.A)throw new P(63);if(16384===(c.mode&61440))throw new P(31);if(32768!==(c.mode&61440))throw new P(28);if(d=cb(c,"w"))throw new P(d);c.s.A(c,{size:0,timestamp:Date.now()})}b&=-131713;e=jb({node:e,path:U(e),flags:b,seekable:!0,position:0,u:e.u,na:[],error:!1});e.u.open&&e.u.open(e);!f.logReadFiles||b&1||(pb||(pb={}),a in
pb||(pb[a]=1));return e},rb=a=>{if(null===a.fd)throw new P(8);a.N&&(a.N=null);try{a.u.close&&a.u.close(a)}catch(b){throw b;}finally{Ya[a.fd]=null}a.fd=null},sb=(a,b,c)=>{if(null===a.fd)throw new P(8);if(!a.seekable||!a.u.H)throw new P(70);if(0!=c&&1!=c&&2!=c)throw new P(28);a.position=a.u.H(a,b,c);a.na=[]},tb=(a,b,c,d,e,g)=>{if(0>d||0>e)throw new P(28);if(null===a.fd)throw new P(8);if(0===(a.flags&2097155))throw new P(8);if(16384===(a.node.mode&61440))throw new P(31);if(!a.u.write)throw new P(28);
a.seekable&&a.flags&1024&&sb(a,0,2);var k="undefined"!=typeof e;if(!k)e=a.position;else if(!a.seekable)throw new P(70);b=a.u.write(a,b,c,d,e,g);k||(a.position+=b);return b},ub=()=>{P||(P=function(a,b){this.node=b;this.ma=function(c){this.F=c};this.ma(a);this.message="FS error"},P.prototype=Error(),P.prototype.constructor=P,[44].forEach(a=>{Ua[a]=new P(a);Ua[a].stack="<generic error, no stack>"}))},vb,wb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},xb=(a,b)=>{a="string"==typeof a?a:U(a);for(b=
b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=O(a+"/"+c);try{V(d,16895,0)}catch(e){}a=d}}return d},yb=(a,b,c,d)=>{a=O(("string"==typeof a?a:U(a))+"/"+b);c=wb(c,d);return V(a,(void 0!==c?c:438)&4095|32768,0)},zb=(a,b,c,d,e,g)=>{var k=b;a&&(a="string"==typeof a?a:U(a),k=b?O(a+"/"+b):a);a=wb(d,e);k=V(k,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}ob(k,a|146);b=qb(k,577);tb(b,c,0,c.length,0,g);rb(b);ob(k,
a)}return k},W=(a,b,c,d)=>{a=O(("string"==typeof a?a:U(a))+"/"+b);b=wb(!!c,!!d);W.$||(W.$=64);var e=W.$++<<8|0;Oa(e,{open:g=>{g.seekable=!1},close:()=>{d&&d.buffer&&d.buffer.length&&d(10)},read:(g,k,r,q)=>{for(var n=0,l=0;l<q;l++){try{var p=c()}catch(v){throw new P(29);}if(void 0===p&&0===n)throw new P(6);if(null===p||void 0===p)break;n++;k[r+l]=p}n&&(g.node.timestamp=Date.now());return n},write:(g,k,r,q)=>{for(var n=0;n<q;n++)try{d(k[r+n])}catch(l){throw new P(29);}q&&(g.node.timestamp=Date.now());
return n}});return lb(a,b,e)},Ab=a=>{if(!(a.ha||a.ia||a.link||a.o)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(w)try{a.o=La(w(a.url)),a.v=a.o.length}catch(b){throw new P(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}},Bb=(a,b,c,d,e)=>{function g(){this.O=!1;this.D=[]}g.prototype.get=
function(l){if(!(l>this.length-1||0>l)){var p=l%this.chunkSize;return this.Z(l/this.chunkSize|0)[p]}};g.prototype.la=function(l){this.Z=l};g.prototype.U=function(){var l=new XMLHttpRequest;l.open("HEAD",c,!1);l.send(null);if(!(200<=l.status&&300>l.status||304===l.status))throw Error("Couldn't load "+c+". Status: "+l.status);var p=Number(l.getResponseHeader("Content-length")),v,x=(v=l.getResponseHeader("Accept-Ranges"))&&"bytes"===v;l=(v=l.getResponseHeader("Content-Encoding"))&&"gzip"===v;var u=1048576;
x||(u=p);var t=this;t.la(A=>{var K=A*u,D=(A+1)*u-1;D=Math.min(D,p-1);if("undefined"==typeof t.D[A]){var Kb=t.D;if(K>D)throw Error("invalid range ("+K+", "+D+") or no bytes requested!");if(D>p-1)throw Error("only "+p+" bytes available! programmer error!");var y=new XMLHttpRequest;y.open("GET",c,!1);p!==u&&y.setRequestHeader("Range","bytes="+K+"-"+D);y.responseType="arraybuffer";y.overrideMimeType&&y.overrideMimeType("text/plain; charset=x-user-defined");y.send(null);if(!(200<=y.status&&300>y.status||
304===y.status))throw Error("Couldn't load "+c+". Status: "+y.status);K=void 0!==y.response?new Uint8Array(y.response||[]):La(y.responseText||"");Kb[A]=K}if("undefined"==typeof t.D[A])throw Error("doXHR failed!");return t.D[A]});if(l||!p)u=p=1,u=p=this.Z(0).length,ka("LazyFiles on gzip forces download of the whole file when length is accessed");this.ea=p;this.da=u;this.O=!0};if("undefined"!=typeof XMLHttpRequest){if(!h)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var k=new g;Object.defineProperties(k,{length:{get:function(){this.O||this.U();return this.ea}},chunkSize:{get:function(){this.O||this.U();return this.da}}});var r=void 0}else r=c,k=void 0;var q=yb(a,b,d,e);k?q.o=k:r&&(q.o=null,q.url=r);Object.defineProperties(q,{v:{get:function(){return this.o.length}}});var n={};Object.keys(q.u).forEach(l=>{var p=q.u[l];n[l]=function(){Ab(q);return p.apply(null,arguments)}});n.read=(l,p,v,x,u)=>{Ab(q);l=l.node.o;if(u>=l.length)p=0;else{x=Math.min(l.length-u,x);
if(l.slice)for(var t=0;t<x;t++)p[v+t]=l[u+t];else for(t=0;t<x;t++)p[v+t]=l.get(u+t);p=x}return p};n.P=()=>{Ab(q);E();throw new P(48);};q.u=n;return q},Db=(a,b,c,d,e,g,k,r,q,n)=>{function l(x){function u(t){n&&n();r||zb(a,b,t,d,e,q);g&&g();za(v)}Cb.qa(x,p,u,()=>{k&&k();za(v)})||u(x)}var p=b?Ka(O(a+"/"+b)):a,v="cp "+p;ya(v);"string"==typeof c?Va(c,x=>l(x),k):l(c)},X={},ib,pb,Eb=void 0;function Y(){Eb+=4;return H[Eb-4>>2]}function Z(a){a=Ya[a];if(!a)throw new P(8);return a}
function Fb(a){if(!noExitRuntime){if(f.onExit)f.onExit(a);ma=!0}da(a,new ja(a))}function db(a,b,c,d){a||(a=this);this.parent=a;this.C=a.C;this.K=null;this.id=Za++;this.name=b;this.mode=c;this.s={};this.u={};this.rdev=d}
Object.defineProperties(db.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},ia:{get:function(){return 16384===(this.mode&61440)}},ha:{get:function(){return 8192===(this.mode&61440)}}});ub();S=Array(4096);kb(Q,"/");V("/tmp",16895,0);V("/home",16895,0);V("/home/web_user",16895,0);
(()=>{V("/dev",16895,0);Oa(259,{read:()=>0,write:(b,c,d,e)=>e});lb("/dev/null",259);Na(1280,Qa);Na(1536,Ra);lb("/dev/tty",1280);lb("/dev/tty1",1536);var a=Ja();W("/dev","random",a);W("/dev","urandom",a);V("/dev/shm",16895,0);V("/dev/shm/tmp",16895,0)})();
(()=>{V("/proc",16895,0);var a=V("/proc/self",16895,0);V("/proc/self/fd",16895,0);kb({C:()=>{var b=Ta(a,"fd",16895,73);b.s={lookup:(c,d)=>{var e=Ya[+d];if(!e)throw new P(8);c={parent:null,C:{aa:"fake"},s:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();var Cb;f.FS_createPath=xb;f.FS_createDataFile=zb;f.FS_createPreloadedFile=Db;f.FS_unlink=nb;f.FS_createLazyFile=Bb;f.FS_createDevice=W;
var Hb={d:function(a,b,c){Eb=c;try{var d=Z(a);switch(b){case 0:var e=Y();return 0>e?-28:jb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Y(),d.flags|=e,0;case 5:return e=Y(),ra[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return H[Gb()>>2]=28,-1;default:return-28}}catch(g){if("undefined"==typeof X||!(g instanceof P))throw g;return-g.F}},h:function(a,b,c){Eb=c;try{var d=Z(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?
0:-59;case 21519:if(!d.tty)return-59;var e=Y();return H[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=Y();if(!d.u.ga)throw new P(59);return d.u.ga(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof X||!(g instanceof P))throw g;return-g.F}},i:function(a,b,c,d){Eb=d;try{b=b?F(qa,b):"";var e=b;if("/"===e.charAt(0))b=e;else{var g=-100===a?"/":Z(a).path;if(0==e.length)throw new P(44);b=O(g+"/"+e)}var k=d?Y():0;return qb(b,c,k).fd}catch(r){if("undefined"==
typeof X||!(r instanceof P))throw r;return-r.F}},j:function(a,b,c){qa.copyWithin(a,b,b+c)},f:function(){E("OOM")},a:Fb,b:function(a){try{var b=Z(a);rb(b);return 0}catch(c){if("undefined"==typeof X||!(c instanceof P))throw c;return c.F}},g:function(a,b,c,d){try{a:{var e=Z(a);a=b;for(var g,k=b=0;k<c;k++){var r=I[a>>2],q=I[a+4>>2];a+=8;var n=e,l=r,p=q,v=g,x=G;if(0>p||0>v)throw new P(28);if(null===n.fd)throw new P(8);if(1===(n.flags&2097155))throw new P(8);if(16384===(n.node.mode&61440))throw new P(31);
if(!n.u.read)throw new P(28);var u="undefined"!=typeof v;if(!u)v=n.position;else if(!n.seekable)throw new P(70);var t=n.u.read(n,x,l,p,v);u||(n.position+=t);var A=t;if(0>A){var K=-1;break a}b+=A;if(A<q)break;"undefined"!==typeof g&&(g+=A)}K=b}I[d>>2]=K;return 0}catch(D){if("undefined"==typeof X||!(D instanceof P))throw D;return D.F}},e:function(a,b,c,d,e){try{b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;if(isNaN(b))return 61;var g=Z(a);sb(g,b,d);Ea=[g.position>>>0,(N=g.position,1<=+Math.abs(N)?
0<N?(Math.min(+Math.floor(N/4294967296),4294967295)|0)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];H[e>>2]=Ea[0];H[e+4>>2]=Ea[1];g.N&&0===b&&0===d&&(g.N=null);return 0}catch(k){if("undefined"==typeof X||!(k instanceof P))throw k;return k.F}},c:function(a,b,c,d){try{a:{var e=Z(a);a=b;for(var g,k=b=0;k<c;k++){var r=I[a>>2],q=I[a+4>>2];a+=8;var n=tb(e,G,r,q,g);if(0>n){var l=-1;break a}b+=n;"undefined"!==typeof g&&(g+=n)}l=b}I[d>>2]=l;return 0}catch(p){if("undefined"==typeof X||!(p instanceof
P))throw p;return p.F}}};
(function(){function a(e){f.asm=e.exports;la=f.asm.k;e=la.buffer;f.HEAP8=G=new Int8Array(e);f.HEAP16=ra=new Int16Array(e);f.HEAP32=H=new Int32Array(e);f.HEAPU8=qa=new Uint8Array(e);f.HEAPU16=new Uint16Array(e);f.HEAPU32=I=new Uint32Array(e);f.HEAPF32=new Float32Array(e);f.HEAPF64=new Float64Array(e);ta.unshift(f.asm.l);za("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return Da().then(function(g){return WebAssembly.instantiate(g,d)}).then(function(g){return g}).then(e,function(g){B("failed to asynchronously prepare wasm: "+
g);E(g)})}var d={a:Hb};ya("wasm-instantiate");if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return B("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return C||"function"!=typeof WebAssembly.instantiateStreaming||Aa()||M.startsWith("file://")||fa||"function"!=typeof fetch?c(b):fetch(M,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){B("wasm streaming compile failed: "+g);B("falling back to ArrayBuffer instantiation");
return c(b)})})})();return{}})();f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.l).apply(null,arguments)};f._main=function(){return(f._main=f.asm.m).apply(null,arguments)};var Gb=f.___errno_location=function(){return(Gb=f.___errno_location=f.asm.n).apply(null,arguments)},Ib=f.stackAlloc=function(){return(Ib=f.stackAlloc=f.asm.p).apply(null,arguments)};f.addRunDependency=ya;f.removeRunDependency=za;f.FS_createPath=xb;f.FS_createDataFile=zb;f.FS_createPreloadedFile=Db;
f.FS_createLazyFile=Bb;f.FS_createDevice=W;f.FS_unlink=nb;var Jb;L=function Lb(){Jb||Mb();Jb||(L=Lb)};function Nb(a){var b=f._main;a=a||[];a.unshift(ca);var c=a.length,d=Ib(4*(c+1)),e=d>>2;a.forEach(k=>{var r=H,q=e++,n=pa(k)+1,l=Ib(n);oa(k,G,l,n);r[q]=l});H[e]=0;try{var g=b(c,d);Fb(g,!0)}catch(k){k instanceof ja||"unwind"==k||da(1,k)}}
function Mb(){function a(){if(!Jb&&(Jb=!0,f.calledRun=!0,!ma)){f.noFSInit||vb||(vb=!0,ub(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?W("/dev","stdin",f.stdin):mb("/dev/tty","/dev/stdin"),f.stdout?W("/dev","stdout",null,f.stdout):mb("/dev/tty","/dev/stdout"),f.stderr?W("/dev","stderr",null,f.stderr):mb("/dev/tty1","/dev/stderr"),qb("/dev/stdin",0),qb("/dev/stdout",1),qb("/dev/stderr",1));$a=!1;Fa(ta);Fa(ua);if(f.onRuntimeInitialized)f.onRuntimeInitialized();Ob&&Nb(b);if(f.postRun)for("function"==
typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();va.unshift(c)}Fa(va)}}var b=b||ba;if(!(0<J)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)wa();Fa(sa);0<J||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Ob=!0;f.noInitialRun&&(Ob=!1);Mb();
