
var f;f||(f=typeof Module !== 'undefined' ? Module : {});var h={},m;for(m in f)f.hasOwnProperty(m)&&(h[m]=f[m]);var v=[],aa="./this.program";function w(a,b){throw b;}var ba=!1,A=!1,ca=!1,da=!1;ba="object"===typeof window;A="function"===typeof importScripts;ca="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;da=!ba&&!ca&&!A;var C="",D,ea,fa,ha,ia;
if(ca)C=A?require("path").dirname(C)+"/":__dirname+"/",D=function(a,b){ha||(ha=require("fs"));ia||(ia=require("path"));a=ia.normalize(a);return ha.readFileSync(a,b?null:"utf8")},fa=function(a){a=D(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||E("Assertion failed: undefined");return a},1<process.argv.length&&(aa=process.argv[1].replace(/\\/g,"/")),v=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=f),process.on("uncaughtException",function(a){if(!(a instanceof ja))throw a;}),process.on("unhandledRejection",
E),w=function(a){process.exit(a)},f.inspect=function(){return"[Emscripten Module object]"};else if(da)"undefined"!=typeof read&&(D=function(a){return read(a)}),fa=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");"object"===typeof a||E("Assertion failed: undefined");return a},"undefined"!=typeof scriptArgs?v=scriptArgs:"undefined"!=typeof arguments&&(v=arguments),"function"===typeof quit&&(w=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===
typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ba||A)A?C=self.location.href:"undefined"!==typeof document&&document.currentScript&&(C=document.currentScript.src),C=0!==C.indexOf("blob:")?C.substr(0,C.lastIndexOf("/")+1):"",D=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},A&&(fa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);
return new Uint8Array(b.response)}),ea=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var la=f.print||console.log.bind(console),F=f.printErr||console.warn.bind(console);for(m in h)h.hasOwnProperty(m)&&(f[m]=h[m]);h=null;f.arguments&&(v=f.arguments);f.thisProgram&&(aa=f.thisProgram);f.quit&&(w=f.quit);var ma;f.wasmBinary&&(ma=f.wasmBinary);
var noExitRuntime=f.noExitRuntime||!0;"object"!==typeof WebAssembly&&E("no native wasm support detected");var na,oa=!1,pa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function qa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&pa)return pa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function ra(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var p=a.charCodeAt(++g);k=65536+((k&1023)<<10)|p&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function sa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function ta(a){var b=sa(a)+1,c=ua(b);ra(a,G,c,b);return c}var va,G,wa,xa,H,ya,za=[],Aa=[],Ba=[],Ca=[];function Da(){var a=f.preRun.shift();za.unshift(a)}var I=0,Ea=null,Fa=null;function Ga(){I++;f.monitorRunDependencies&&f.monitorRunDependencies(I)}
function Ha(){I--;f.monitorRunDependencies&&f.monitorRunDependencies(I);if(0==I&&(null!==Ea&&(clearInterval(Ea),Ea=null),Fa)){var a=Fa;Fa=null;a()}}f.preloadedImages={};f.preloadedAudios={};function E(a){if(f.onAbort)f.onAbort(a);F(a);oa=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ia(){return J.startsWith("data:application/octet-stream;base64,")}var J="svg2ass.wasm";if(!Ia()){var Ja=J;J=f.locateFile?f.locateFile(Ja,C):C+Ja}
function Ka(){var a=J;try{if(a==J&&ma)return new Uint8Array(ma);if(fa)return fa(a);throw"both async and sync fetching of the wasm failed";}catch(b){E(b)}}
function La(){if(!ma&&(ba||A)){if("function"===typeof fetch&&!J.startsWith("file://"))return fetch(J,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+J+"'";return a.arrayBuffer()}).catch(function(){return Ka()});if(ea)return new Promise(function(a,b){ea(J,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ka()})}var K,Ma;
function Na(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.sa;"number"===typeof c?void 0===b.N?ya.get(c)():ya.get(c)(b.N):c(void 0===b.N?null:b.N)}}}function Oa(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function L(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Oa(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function Pa(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Qa(a){if("/"===a)return"/";a=L(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Ra(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ca)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){E("randomDevice")}}
function Sa(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Oa(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Ta=[];function Ua(a,b){Ta[a]={input:[],output:[],J:b};Va(a,Wa)}
var Wa={open:function(a){var b=Ta[a.node.rdev];if(!b)throw new M(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.J.flush(a.tty)},flush:function(a){a.tty.J.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.J.Z)throw new M(60);for(var e=0,g=0;g<d;g++){try{var k=a.tty.J.Z(a.tty)}catch(p){throw new M(29);}if(void 0===k&&0===e)throw new M(6);if(null===k||void 0===k)break;e++;b[c+g]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.J.S)throw new M(60);try{for(var e=
0;e<d;e++)a.tty.J.S(a.tty,b[c+e])}catch(g){throw new M(29);}d&&(a.node.timestamp=Date.now());return e}},Ya={Z:function(a){if(!a.input.length){var b=null;if(ca){var c=Buffer.K?Buffer.K(256):new Buffer(256),d=0;try{d=ha.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&
(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Xa(b)}return a.input.shift()},S:function(a,b){null===b||10===b?(la(qa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(la(qa(a.output,0)),a.output=[])}},Za={S:function(a,b){null===b||10===b?(F(qa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(F(qa(a.output,0)),a.output=[])}},N={C:null,D:function(){return N.createNode(null,"/",16895,0)},createNode:function(a,
b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new M(63);N.C||(N.C={dir:{node:{G:N.u.G,B:N.u.B,lookup:N.u.lookup,M:N.u.M,rename:N.u.rename,unlink:N.u.unlink,rmdir:N.u.rmdir,readdir:N.u.readdir,symlink:N.u.symlink},stream:{H:N.v.H}},file:{node:{G:N.u.G,B:N.u.B},stream:{H:N.v.H,read:N.v.read,write:N.v.write,U:N.v.U,ba:N.v.ba,ea:N.v.ea}},link:{node:{G:N.u.G,B:N.u.B,readlink:N.u.readlink},stream:{}},W:{node:{G:N.u.G,B:N.u.B},stream:$a}});c=ab(a,b,c,d);16384===(c.mode&61440)?(c.u=N.C.dir.node,c.v=
N.C.dir.stream,c.s={}):32768===(c.mode&61440)?(c.u=N.C.file.node,c.v=N.C.file.stream,c.A=0,c.s=null):40960===(c.mode&61440)?(c.u=N.C.link.node,c.v=N.C.link.stream):8192===(c.mode&61440)&&(c.u=N.C.W.node,c.v=N.C.W.stream);c.timestamp=Date.now();a&&(a.s[b]=c,a.timestamp=c.timestamp);return c},ta:function(a){return a.s?a.s.subarray?a.s.subarray(0,a.A):new Uint8Array(a.s):new Uint8Array(0)},X:function(a,b){var c=a.s?a.s.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),
c=a.s,a.s=new Uint8Array(b),0<a.A&&a.s.set(c.subarray(0,a.A),0))},ma:function(a,b){if(a.A!=b)if(0==b)a.s=null,a.A=0;else{var c=a.s;a.s=new Uint8Array(b);c&&a.s.set(c.subarray(0,Math.min(b,a.A)));a.A=b}},u:{G:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.A:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);
b.ctime=new Date(a.timestamp);b.ha=4096;b.blocks=Math.ceil(b.size/b.ha);return b},B:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&N.ma(a,b.size)},lookup:function(){throw bb[44];},M:function(a,b,c,d){return N.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=O(b,c)}catch(g){}if(d)for(var e in d.s)throw new M(55);}delete a.parent.s[a.name];a.parent.timestamp=Date.now();a.name=c;b.s[c]=a;b.timestamp=a.parent.timestamp;
a.parent=b},unlink:function(a,b){delete a.s[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=O(a,b),d;for(d in c.s)throw new M(55);delete a.s[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.s)a.s.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=N.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new M(28);return a.link}},v:{read:function(a,b,c,d,e){var g=a.node.s;if(e>=a.node.A)return 0;a=Math.min(a.node.A-
e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.s||a.s.subarray)){if(g)return a.s=b.subarray(c,c+d),a.A=d;if(0===a.A&&0===e)return a.s=b.slice(c,c+d),a.A=d;if(e+d<=a.A)return a.s.set(b.subarray(c,c+d),e),d}N.X(a,e+d);if(a.s.subarray&&b.subarray)a.s.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.s[e+g]=b[c+g];a.A=Math.max(a.A,e+d);return d},H:function(a,b,c){1===
c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.A);if(0>b)throw new M(28);return b},U:function(a,b,c){N.X(a.node,b+c);a.node.A=Math.max(a.node.A,b+c)},ba:function(a,b,c,d,e,g){if(0!==b)throw new M(28);if(32768!==(a.node.mode&61440))throw new M(43);a=a.node.s;if(g&2||a.buffer!==va){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;g=65536*Math.ceil(c/65536);for(b=cb(g);c<g;)G[b+c++]=0;c=b;if(!c)throw new M(48);G.set(a,c)}else d=!1,c=a.byteOffset;
return{wa:c,qa:d}},ea:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new M(43);if(e&2)return 0;N.v.write(a,b,0,d,c,!1);return 0}}},db=null,eb={},fb=[],gb=1,P=null,hb=!0,Q={},M=null,bb={};
function R(a,b){a=Sa("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Y:!0,T:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.T)throw new M(32);a=Oa(a.split("/").filter(function(k){return!!k}),!1);var e=db;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=O(e,a[d]);c=L(c+"/"+a[d]);e.L&&(!g||g&&b.Y)&&(e=e.L.root);if(!g||b.O)for(g=0;40960===(e.mode&61440);)if(e=ib(c),c=Sa(Pa(c),e),e=R(c,{T:b.T}).node,40<g++)throw new M(32);}return{path:c,node:e}}
function S(a){for(var b;;){if(a===a.parent)return a=a.D.da,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function jb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%P.length}function O(a,b){var c;if(c=(c=kb(a,"x"))?c:a.u.lookup?0:2)throw new M(c,a);for(c=P[jb(a.id,b)];c;c=c.I){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.u.lookup(a,b)}function ab(a,b,c,d){a=new lb(a,b,c,d);b=jb(a.parent.id,a.name);a.I=P[b];return P[b]=a}
var mb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function nb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function kb(a,b){if(hb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function ob(a,b){try{return O(a,b),20}catch(c){}return kb(a,"wx")}function pb(a){var b=4096;for(a=a||0;a<=b;a++)if(!fb[a])return a;throw new M(33);}
function qb(a,b){rb||(rb=function(){},rb.prototype={});var c=new rb,d;for(d in a)c[d]=a[d];a=c;b=pb(b);a.fd=b;return fb[b]=a}var $a={open:function(a){a.v=eb[a.node.rdev].v;a.v.open&&a.v.open(a)},H:function(){throw new M(70);}};function Va(a,b){eb[a]={v:b}}
function sb(a,b){var c="/"===b,d=!b;if(c&&db)throw new M(10);if(!c&&!d){var e=R(b,{Y:!1});b=e.path;e=e.node;if(e.L)throw new M(10);if(16384!==(e.mode&61440))throw new M(54);}b={type:a,va:{},da:b,la:[]};a=a.D(b);a.D=b;b.root=a;c?db=a:e&&(e.L=b,e.D&&e.D.la.push(b))}function tb(a,b,c){var d=R(a,{parent:!0}).node;a=Qa(a);if(!a||"."===a||".."===a)throw new M(28);var e=ob(d,a);if(e)throw new M(e);if(!d.u.M)throw new M(63);return d.u.M(d,a,b,c)}function T(a){return tb(a,16895,0)}
function ub(a,b,c){"undefined"===typeof c&&(c=b,b=438);return tb(a,b|8192,c)}function vb(a,b){if(!Sa(a))throw new M(44);var c=R(b,{parent:!0}).node;if(!c)throw new M(44);b=Qa(b);var d=ob(c,b);if(d)throw new M(d);if(!c.u.symlink)throw new M(63);c.u.symlink(c,b,a)}
function wb(a){var b=R(a,{parent:!0}).node,c=Qa(a),d=O(b,c);a:{try{var e=O(b,c)}catch(k){e=k.F;break a}var g=kb(b,"wx");e=g?g:16384===(e.mode&61440)?31:0}if(e)throw new M(e);if(!b.u.unlink)throw new M(63);if(d.L)throw new M(10);try{Q.willDeletePath&&Q.willDeletePath(a)}catch(k){F("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+k.message)}b.u.unlink(b,c);b=jb(d.parent.id,d.name);if(P[b]===d)P[b]=d.I;else for(b=P[b];b;){if(b.I===d){b.I=d.I;break}b=b.I}try{if(Q.onDeletePath)Q.onDeletePath(a)}catch(k){F("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+k.message)}}function ib(a){a=R(a).node;if(!a)throw new M(44);if(!a.u.readlink)throw new M(28);return Sa(S(a.parent),a.u.readlink(a))}function xb(a,b){a="string"===typeof a?R(a,{O:!0}).node:a;if(!a.u.B)throw new M(63);a.u.B(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function V(a,b,c,d){if(""===a)throw new M(44);if("string"===typeof b){var e=mb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=L(a);try{g=R(a,{O:!(b&131072)}).node}catch(k){}}e=!1;if(b&64)if(g){if(b&128)throw new M(20);}else g=tb(a,c,0),e=!0;if(!g)throw new M(44);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&16384!==(g.mode&61440))throw new M(54);if(!e&&(c=g?40960===(g.mode&61440)?32:
16384===(g.mode&61440)&&("r"!==nb(b)||b&512)?31:kb(g,nb(b)):44))throw new M(c);if(b&512){c=g;c="string"===typeof c?R(c,{O:!0}).node:c;if(!c.u.B)throw new M(63);if(16384===(c.mode&61440))throw new M(31);if(32768!==(c.mode&61440))throw new M(28);if(e=kb(c,"w"))throw new M(e);c.u.B(c,{size:0,timestamp:Date.now()})}b&=-131713;d=qb({node:g,path:S(g),flags:b,seekable:!0,position:0,v:g.v,pa:[],error:!1},d);d.v.open&&d.v.open(d);!f.logReadFiles||b&1||(yb||(yb={}),a in yb||(yb[a]=1,F("FS.trackingDelegate error on read file: "+
a)));try{Q.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),Q.onOpenFile(a,g))}catch(k){F("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+k.message)}return d}function zb(a){if(null===a.fd)throw new M(8);a.P&&(a.P=null);try{a.v.close&&a.v.close(a)}catch(b){throw b;}finally{fb[a.fd]=null}a.fd=null}function Ab(a,b,c){if(null===a.fd)throw new M(8);if(!a.seekable||!a.v.H)throw new M(70);if(0!=c&&1!=c&&2!=c)throw new M(28);a.position=a.v.H(a,b,c);a.pa=[]}
function Bb(a,b,c,d,e,g){if(0>d||0>e)throw new M(28);if(null===a.fd)throw new M(8);if(0===(a.flags&2097155))throw new M(8);if(16384===(a.node.mode&61440))throw new M(31);if(!a.v.write)throw new M(28);a.seekable&&a.flags&1024&&Ab(a,0,2);var k="undefined"!==typeof e;if(!k)e=a.position;else if(!a.seekable)throw new M(70);b=a.v.write(a,b,c,d,e,g);k||(a.position+=b);try{if(a.path&&Q.onWriteToFile)Q.onWriteToFile(a.path)}catch(p){F("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+
p.message)}return b}function Cb(){M||(M=function(a,b){this.node=b;this.na=function(c){this.F=c};this.na(a);this.message="FS error"},M.prototype=Error(),M.prototype.constructor=M,[44].forEach(function(a){bb[a]=new M(a);bb[a].stack="<generic error, no stack>"}))}var Db;function Eb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function Fb(a,b){a="string"===typeof a?a:S(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=L(a+"/"+c);try{T(d)}catch(e){}a=d}}return d}
function Gb(a,b,c,d){a=L(("string"===typeof a?a:S(a))+"/"+b);c=Eb(c,d);return tb(a,(void 0!==c?c:438)&4095|32768,0)}function Hb(a,b,c,d,e,g){a=b?L(("string"===typeof a?a:S(a))+"/"+b):a;d=Eb(d,e);e=tb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}xb(e,d|146);a=V(e,577);Bb(a,c,0,c.length,0,g);zb(a);xb(e,d)}return e}
function W(a,b,c,d){a=L(("string"===typeof a?a:S(a))+"/"+b);b=Eb(!!c,!!d);W.aa||(W.aa=64);var e=W.aa++<<8|0;Va(e,{open:function(g){g.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(g,k,p,n){for(var t=0,l=0;l<n;l++){try{var q=c()}catch(x){throw new M(29);}if(void 0===q&&0===t)throw new M(6);if(null===q||void 0===q)break;t++;k[p+l]=q}t&&(g.node.timestamp=Date.now());return t},write:function(g,k,p,n){for(var t=0;t<n;t++)try{d(k[p+t])}catch(l){throw new M(29);}n&&(g.node.timestamp=
Date.now());return t}});return ub(a,b,e)}function Ib(a){if(!(a.ja||a.ka||a.link||a.s)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(D)try{a.s=Xa(D(a.url)),a.A=a.s.length}catch(b){throw new M(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function Jb(a,b,c,d,e){function g(){this.R=!1;this.K=[]}g.prototype.get=function(l){if(!(l>this.length-1||0>l)){var q=l%this.chunkSize;return this.$(l/this.chunkSize|0)[q]}};g.prototype.oa=function(l){this.$=l};g.prototype.V=function(){var l=new XMLHttpRequest;l.open("HEAD",c,!1);l.send(null);if(!(200<=l.status&&300>l.status||304===l.status))throw Error("Couldn't load "+c+". Status: "+l.status);var q=Number(l.getResponseHeader("Content-length")),x,y=(x=l.getResponseHeader("Accept-Ranges"))&&"bytes"===
x;l=(x=l.getResponseHeader("Content-Encoding"))&&"gzip"===x;var u=1048576;y||(u=q);var r=this;r.oa(function(z){var ka=z*u,U=(z+1)*u-1;U=Math.min(U,q-1);if("undefined"===typeof r.K[z]){var Sb=r.K;if(ka>U)throw Error("invalid range ("+ka+", "+U+") or no bytes requested!");if(U>q-1)throw Error("only "+q+" bytes available! programmer error!");var B=new XMLHttpRequest;B.open("GET",c,!1);q!==u&&B.setRequestHeader("Range","bytes="+ka+"-"+U);"undefined"!=typeof Uint8Array&&(B.responseType="arraybuffer");
B.overrideMimeType&&B.overrideMimeType("text/plain; charset=x-user-defined");B.send(null);if(!(200<=B.status&&300>B.status||304===B.status))throw Error("Couldn't load "+c+". Status: "+B.status);ka=void 0!==B.response?new Uint8Array(B.response||[]):Xa(B.responseText||"");Sb[z]=ka}if("undefined"===typeof r.K[z])throw Error("doXHR failed!");return r.K[z]});if(l||!q)u=q=1,u=q=this.$(0).length,la("LazyFiles on gzip forces download of the whole file when length is accessed");this.ga=q;this.fa=u;this.R=
!0};if("undefined"!==typeof XMLHttpRequest){if(!A)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var k=new g;Object.defineProperties(k,{length:{get:function(){this.R||this.V();return this.ga}},chunkSize:{get:function(){this.R||this.V();return this.fa}}});var p=void 0}else p=c,k=void 0;var n=Gb(a,b,d,e);k?n.s=k:p&&(n.s=null,n.url=p);Object.defineProperties(n,{A:{get:function(){return this.s.length}}});var t={};Object.keys(n.v).forEach(function(l){var q=
n.v[l];t[l]=function(){Ib(n);return q.apply(null,arguments)}});t.read=function(l,q,x,y,u){Ib(n);l=l.node.s;if(u>=l.length)return 0;y=Math.min(l.length-u,y);if(l.slice)for(var r=0;r<y;r++)q[x+r]=l[u+r];else for(r=0;r<y;r++)q[x+r]=l.get(u+r);return y};n.v=t;return n}
function Kb(a,b,c,d,e,g,k,p,n,t){function l(y){function u(z){t&&t();p||Hb(a,b,z,d,e,n);g&&g();Ha(x)}var r=!1;f.preloadPlugins.forEach(function(z){!r&&z.canHandle(q)&&(z.handle(y,q,u,function(){k&&k();Ha(x)}),r=!0)});r||u(y)}Lb.ua();var q=b?Sa(L(a+"/"+b)):a,x="cp "+q;Ga(x);"string"==typeof c?Lb.ra(c,function(y){l(y)},k):l(c)}var X={},rb,yb,Mb=void 0;function Y(){Mb+=4;return H[Mb-4>>2]}function Z(a){a=fb[a];if(!a)throw new M(8);return a}
function lb(a,b,c,d){a||(a=this);this.parent=a;this.D=a.D;this.L=null;this.id=gb++;this.name=b;this.mode=c;this.u={};this.v={};this.rdev=d}Object.defineProperties(lb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},ka:{get:function(){return 16384===(this.mode&61440)}},ja:{get:function(){return 8192===(this.mode&61440)}}});Cb();P=Array(4096);
sb(N,"/");T("/tmp");T("/home");T("/home/web_user");(function(){T("/dev");Va(259,{read:function(){return 0},write:function(b,c,d,e){return e}});ub("/dev/null",259);Ua(1280,Ya);Ua(1536,Za);ub("/dev/tty",1280);ub("/dev/tty1",1536);var a=Ra();W("/dev","random",a);W("/dev","urandom",a);T("/dev/shm");T("/dev/shm/tmp")})();
(function(){T("/proc");var a=T("/proc/self");T("/proc/self/fd");sb({D:function(){var b=ab(a,"fd",16895,73);b.u={lookup:function(c,d){var e=fb[+d];if(!e)throw new M(8);c={parent:null,D:{da:"fake"},u:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();var Lb;f.FS_createPath=Fb;f.FS_createDataFile=Hb;f.FS_createPreloadedFile=Kb;f.FS_createLazyFile=Jb;f.FS_createDevice=W;f.FS_unlink=wb;function Xa(a){var b=Array(sa(a)+1);a=ra(a,b,0,b.length);b.length=a;return b}
var Pb={b:function(a,b,c){Mb=c;try{var d=Z(a);switch(b){case 0:var e=Y();return 0>e?-28:V(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Y(),d.flags|=e,0;case 12:return e=Y(),xa[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return H[Nb()>>2]=28,-1;default:return-28}}catch(g){return"undefined"!==typeof X&&g instanceof M||E(g),-g.F}},g:function(a,b,c){Mb=c;try{var d=Z(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?
0:-59;case 21519:if(!d.tty)return-59;var e=Y();return H[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=Y();if(!d.v.ia)throw new M(59);return d.v.ia(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:E("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof X&&g instanceof M||E(g),-g.F}},j:function(a,b,c){Mb=c;try{var d=a?qa(wa,a,void 0):"",e=c?Y():0;return V(d,b,e).fd}catch(g){return"undefined"!==typeof X&&g instanceof M||E(g),-g.F}},e:function(a,b,c){wa.copyWithin(a,
b,b+c)},f:function(){E("OOM")},a:function(a){Ob(a)},d:function(a){try{var b=Z(a);zb(b);return 0}catch(c){return"undefined"!==typeof X&&c instanceof M||E(c),c.F}},h:function(a,b,c,d){try{a:{for(var e=Z(a),g=a=0;g<c;g++){var k=H[b+(8*g+4)>>2],p=e,n=H[b+8*g>>2],t=k,l=void 0,q=G;if(0>t||0>l)throw new M(28);if(null===p.fd)throw new M(8);if(1===(p.flags&2097155))throw new M(8);if(16384===(p.node.mode&61440))throw new M(31);if(!p.v.read)throw new M(28);var x="undefined"!==typeof l;if(!x)l=p.position;else if(!p.seekable)throw new M(70);
var y=p.v.read(p,q,n,t,l);x||(p.position+=y);var u=y;if(0>u){var r=-1;break a}a+=u;if(u<k)break}r=a}H[d>>2]=r;return 0}catch(z){return"undefined"!==typeof X&&z instanceof M||E(z),z.F}},i:function(a,b,c,d,e){try{var g=Z(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Ab(g,a,d);Ma=[g.position>>>0,(K=g.position,1<=+Math.abs(K)?0<K?(Math.min(+Math.floor(K/4294967296),4294967295)|0)>>>0:~~+Math.ceil((K-+(~~K>>>0))/4294967296)>>>0:0)];H[e>>2]=Ma[0];H[e+4>>2]=Ma[1];g.P&&
0===a&&0===d&&(g.P=null);return 0}catch(k){return"undefined"!==typeof X&&k instanceof M||E(k),k.F}},c:function(a,b,c,d){try{a:{for(var e=Z(a),g=a=0;g<c;g++){var k=Bb(e,G,H[b+8*g>>2],H[b+(8*g+4)>>2],void 0);if(0>k){var p=-1;break a}a+=k}p=a}H[d>>2]=p;return 0}catch(n){return"undefined"!==typeof X&&n instanceof M||E(n),n.F}}};
(function(){function a(e){f.asm=e.exports;na=f.asm.k;va=e=na.buffer;f.HEAP8=G=new Int8Array(e);f.HEAP16=xa=new Int16Array(e);f.HEAP32=H=new Int32Array(e);f.HEAPU8=wa=new Uint8Array(e);f.HEAPU16=new Uint16Array(e);f.HEAPU32=new Uint32Array(e);f.HEAPF32=new Float32Array(e);f.HEAPF64=new Float64Array(e);ya=f.asm.m;Aa.unshift(f.asm.l);Ha("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return La().then(function(g){return WebAssembly.instantiate(g,d)}).then(e,function(g){F("failed to asynchronously prepare wasm: "+
g);E(g)})}var d={a:Pb};Ga("wasm-instantiate");if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return F("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ma||"function"!==typeof WebAssembly.instantiateStreaming||Ia()||J.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(J,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){F("wasm streaming compile failed: "+g);F("falling back to ArrayBuffer instantiation");
return c(b)})})})();return{}})();f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.l).apply(null,arguments)};f._main=function(){return(f._main=f.asm.n).apply(null,arguments)};var Nb=f.___errno_location=function(){return(Nb=f.___errno_location=f.asm.o).apply(null,arguments)},cb=f._malloc=function(){return(cb=f._malloc=f.asm.p).apply(null,arguments)},ua=f.stackAlloc=function(){return(ua=f.stackAlloc=f.asm.q).apply(null,arguments)};f.addRunDependency=Ga;f.removeRunDependency=Ha;
f.FS_createPath=Fb;f.FS_createDataFile=Hb;f.FS_createPreloadedFile=Kb;f.FS_createLazyFile=Jb;f.FS_createDevice=W;f.FS_unlink=wb;var Qb;function ja(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Fa=function Rb(){Qb||Tb();Qb||(Fa=Rb)};
function Tb(a){function b(){if(!Qb&&(Qb=!0,f.calledRun=!0,!oa)){f.noFSInit||Db||(Db=!0,Cb(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?W("/dev","stdin",f.stdin):vb("/dev/tty","/dev/stdin"),f.stdout?W("/dev","stdout",null,f.stdout):vb("/dev/tty","/dev/stdout"),f.stderr?W("/dev","stderr",null,f.stderr):vb("/dev/tty1","/dev/stderr"),V("/dev/stdin",0),V("/dev/stdout",1),V("/dev/stderr",1));Na(Aa);hb=!1;Na(Ba);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(Ub){var c=a,d=f._main;
c=c||[];var e=c.length+1,g=ua(4*(e+1));H[g>>2]=ta(aa);for(var k=1;k<e;k++)H[(g>>2)+k]=ta(c[k-1]);H[(g>>2)+e]=0;try{var p=d(e,g);Ob(p,!0)}catch(n){n instanceof ja||"unwind"==n||((c=n)&&"object"===typeof n&&n.stack&&(c=[n,n.stack]),F("exception thrown: "+c),w(1,n))}finally{}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)c=f.postRun.shift(),Ca.unshift(c);Na(Ca)}}a=a||v;if(!(0<I)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Da();
Na(za);0<I||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}f.run=Tb;function Ob(a,b){if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){if(f.onExit)f.onExit(a);oa=!0}w(a,new ja(a))}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Ub=!0;f.noInitialRun&&(Ub=!1);Tb();
